site:
  title: Antora GitHub Pages Demo
  start_page: antora-gh-pages-demo::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
ui:
  bundle:
    url: ./ui-bundle.zip
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    # add @asciidoctor/tabs files during generation
    - path: css/vendor/tabs.css
      contents: './node_modules/@asciidoctor/tabs/dist/css/tabs.css'
    - path: js/vendor/tabs.js
      contents: './node_modules/@asciidoctor/tabs/dist/js/tabs.js'
    - path: partials/footer-scripts.hbs
      contents: |
        <script id="site-script" src="{{{uiRootPath}}}/js/site.js" data-ui-root-path="{{{uiRootPath}}}"></script>
        <script async src="{{{uiRootPath}}}/js/vendor/highlight.js"></script>
        <script async src="{{{uiRootPath}}}/js/vendor/tabs.js"></script>
        {{#if env.SITE_SEARCH_PROVIDER}}
        {{> search-scripts}}
        {{/if}}
    - path: partials/head-styles.hbs
      contents: |
        <link rel="stylesheet" href="{{{uiRootPath}}}/css/site.css">
        <link rel="stylesheet" href="{{{uiRootPath}}}/css/vendor/tabs.css">
    # # https://docs.antora.org/antora/latest/publish-to-github-pages/
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
output:
  clean: true
antora:
  extensions:
    - '@antora/lunr-extension'
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
