name: Publish Pages via GH CLI

on:
  #  push:
  #    branches:
  #      - main

  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages-gh-cli"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read    # to read the repository itself
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Install Dependencies
        run: npm ci
      - name: Generate Site
        run: npx antora antora-playbook.yml
      - name: Compress artifact
        run: tar -cvf page-artifact.tar build/site
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: page-artifact
          path: page-artifact.tar

  configure:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to configure to Pages
    needs: build
    steps:
      - name: Check Page Exists
        id: exists
        run: |
          if gh api --silent \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GH_REPOSITORY}/pages" ; then
            echo "page_configured=true" >> "$GITHUB_OUTPUT"
          else
            echo "page_configured=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          GH_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
      - name: Setup Page
        run: |
          jq --null-input --raw-output \
            '{ "build_type": "workflow" }' \
            > request.json

          method=POST
          if [[ ${PAGE_CONFIGURED} = true ]]; then
            method=PUT
          fi

          gh api \
            --method ${method} \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GH_REPOSITORY}/pages" \
            --input request.json
        env:
          PAGE_CONFIGURED: ${{ steps.exists.outputs.page_configured }}
          GH_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}

  deploy:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    needs: configure
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: page-artifact
          path: page-artifact.tar
      - name: Deploy to GitHub Pages
        run: |
          gh api \
          --method POST \
          --header "Accept: application/vnd.github+json" \
          --header "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/${GH_REPOSITORY}/pages/deployment" \
          -f artifact_url=page-artifact.tar \
          -f environment='github-pages' \
          -f pages_build_version='${{ github.sha }}' \
          -f oidc_token="${GH_TOKEN}"
        env:
          GH_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
