# yaml-language-server:$schema=https://json.schemastore.org/github-workflow.json
# https://docs.github.com/en/actions/writing-workflows
name: Setup Pages via GH CLI

# yamllint disable-line rule:truthy
on:
  #  push:
  #    branches:
  #      - main

  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages-gh-cli-setup"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read    # to read the repository itself
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Extract Tool Versions
        id: tool-versions
        run: |
          node_version=$(grep -F 'node' .mise.toml | cut -d '=' -f2 | xargs)
          echo "node_version=${node_version}" >> "$GITHUB_OUTPUT"
      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.tool-versions.outputs.node_version }}
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install Dependencies
        run: npm ci
      - name: Generate Site
        run: npx antora antora-playbook.yml
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: page-artifact
          path: build/site
          if-no-files-found: error

  configure:
    runs-on: ubuntu-latest
    permissions:
      contents: read    # to read the repository itself
      pages: write      # to configure to Pages
    needs: build
    steps:
      - name: Check Page Exists
        id: exists
        run: |
          if gh api --silent \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${GH_REPOSITORY}/pages" ; then
            echo "page_configured=true" >> "$GITHUB_OUTPUT"
          else
            echo "page_configured=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          GH_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
      - name: Setup Page
        run: |
          method=POST
          if [[ ${PAGE_CONFIGURED} = true ]]; then
            method=PUT
          fi

          curl -L \
            -X ${method} \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${GH_REPOSITORY}/pages \
            -d '{ "build_type": "workflow" }'

# Causes a Resource not accessible by integration (HTTP 403) error
# Probably related to https://github.com/orgs/community/discussions/35595
#          jq --null-input --raw-output \
#            '{ "build_type": "workflow" }' \
#            > request.json
#          gh api \
#            --method ${method} \
#            --header "Accept: application/vnd.github+json" \
#            --header "X-GitHub-Api-Version: 2022-11-28" \
#            "/repos/${GH_REPOSITORY}/pages" \
#            --input request.json
        env:
          PAGE_CONFIGURED: ${{ steps.exists.outputs.page_configured }}
          GH_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
